<?php
$birthPlaces = [
    "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Pune", "Jaipur", "Surat",
    "Kanpur", "Lucknow", "Nagpur", "Patna", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Vadodara", "Firozabad",
    "Ludhiana", "Rajkot", "Agra", "Siliguri", "Nashik", "Faridabad", "Patiala", "Meerut", "Kalyan", "Vasai",
    "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", "Allahabad", "Ranchi", "Howrah",
    "Coimbatore", "Jabalpur", "Gwalior", "Vijayawada", "Jodhpur", "Madurai", "Raipur", "Kota", "Guwahati",
    "Chandigarh", "Solapur", "Hubli", "Mysore", "Tiruchirappalli", "Bareilly", "Aligarh", "Tiruppur", "Moradabad",
    "Bagalkote", "Jamkhandi", "Mudhola", "Badami", "Bilagi", "Hunagunda", "Ilkal", "Rabkavi Banhatti", 
    "Guledgudda", "Ballari", "Kurugodu", "Kampli", "Sanduru", "Siraguppa", "Belagavi", "Athani", 
    "Bailhongal", "Chikkodi", "Gokak", "Khanapura", "Mudalgi", "Nippani", "Rayabaga", "Savadatti",
    "Ramadurga", "Kagawada", "Hukkeri", "Kitturu", "Bengaluru Urban", "Hebbala", "Kengeri", 
    "Krishnarajapura", "Anekal", "Yelahanka", "Bengaluru Rural", "Nelamangala", "Doddaballapura", 
    "Devanahalli", "Hosakote", "Bidar", "Aurad", "Basavakalyana", "Bhalki", "Chitgoppa", "Hulsuru", 
    "Humnabad", "Kamalanagara", "Chamarajanagara", "Gundlupete", "Kollegala", "Yelanduru", 
    "Hanuru", "Chikkaballapura", "Bagepalli", "Chintamani", "Gauribidanuru", "Gudibanda", "Sidlaghatta", 
    "Cheluru", "Chikkamagaluru", "Kaduru", "Koppa", "Mudigere", "Narasimharajapura", "Sringeri", 
    "Tarikere", "Ajjampura", "Kalasa", "Chitradurga", "Challakere", "Hiriyur", "Holalkere", 
    "Hosadurga", "Molakalmuru", "Dakshina Kannada", "Mangaluru", "Ullal", "Manipal", "Mulki", "Moodbidri", 
    "Bantwala", "Belathangadi", "Putturu", "Sulya", "Kadaba", "Davanagere", "Harihara", "Channagiri", 
    "Honnali", "Nyamathi", "Jagaluru", "Kalghatgi", "Dharwad", "Hubballi", 
    "Kundagolu", "Navalgunda", "Alnavara", "Annigeri", "Gadag", "Naragunda", "Mundaragi", "Rona", 
    "Gajendragada", "Lakshmeshwara", "Shirahatti", "Hassan", "Arasikere", "Channarayapattana", 
    "Holenarsipura", "Sakleshpura", "Aluru", "Arakalagudu", "Beluru", "Haveri", "Ranibennur", 
    "Byadgi", "Hangala", "Savanuru", "Hirekeruru", "Shiggavi", "Rattihalli", "Kalaburagi",
    "Afzalpura", "Alanda", "Chincholi", "Chitapura", "Jevargi", "Sedam", "Kamalapura", "Shahabad", 
    "Kalgi", "Yedrami", "Kodagu", "Madikeri", "Somawarapete", "Virajapete", "Ponnammapete", 
    "Kushalnagara", "Kolar", "Bangarapete", "Maluru", "Mulabagilu", "Srinivasapura", 
    "Kolar Gold Fields (Robertsonpete)", "Koppala", "Gangavathi", "Kushtagi", "Yelaburga", 
    "Kanakagiri", "Karatagi", "Kukanuru", "Mandya", "Madduru", "Malavalli", "Srirangapattana", 
    "Krishnarajapete", "Nagamangala", "Pandavapura", "Mysuru", "Hunasuru", "Krishnarajanagara", 
    "Nanjanagodu", "Heggadadevanakote", "Piriyapattana", "Tirumakudalu Narasipura",
    "Saraguru,Saligrama", "Raichuru", "Sindhanuru", "Manvi", "Devadurga", "Lingasaguru",
    "Mudgal", "Maski", "Sirawara", "Ramanagara", "Magadi", "Kanakapura", "Channapattana", "Harohalli",
    "Shivamogga", "Sagara", "Bhadravathi", "Hosanagara", "Shikaripura", "Soraba", "Tirthahalli", 
    "Tumakuru", "Chikkanayakanahalli", "Kunigal", "Madhugiri", "Sira", "Tipturu", "Gubbi", "Koratagere", 
    "Pavagada", "Turuvekere", "Udupi", "Kapu", "Bynduru", "Karkala", "Kundapura", "Hebri", "Brahmavara", 
    "Uttara Kannada", "Karwara", "Sirsi", "Joida", "Dandeli", "Bhatkal", "Kumta", "Ankola", "Haliyal", 
    "Honnavara", "Mundagodu", "Siddapura", "Yellapura", "Vijayapura", "Indi", "Basavana Bagewadi", 
    "Sindgi", "Muddebihala", "Talikote", "Devara Hipparagi", "Chadchana", "Tikote", "Babaleshwara", 
    "Kolhara", "Nidagundi", "Alamela", "Yadagiri", "Shahapura", "Surapura", "Gurmitkala", "Vadagera", 
    "Hunsagi", "Vijayanagara", "Hosapete", "Hagaribommanahalli", "Harapanahalli", "Hoovina Hadagali", 
    "Kudligi", "Kotturu","Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", 
    "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thrissur", "Wayanad","Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul", "Erode", "Kallakurichi", 
    "Kancheepuram", "Karur", "Krishnagiri", "Madurai", "Mayiladuthurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", 
    "Pudukottai", "Ramanathapuram", "Ranipet", "Salem", "Sivagangai", "Tenkasi", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", 
    "Tirunelveli", "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Vellore", "Viluppuram", "Virudhunagar",
"Ahmednagar", "Akola", "Amravati", "Aurangabad", "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dhule", 
    "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", 
    "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabad", "Palghar", "Parbhani", 
    "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", 
    "Washim", "Yavatmal"
];
echo json_encode($birthPlaces);
?>
